version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - whitespace
  disable:
    - goconst
    - gosec
    - nakedret
    - prealloc
    - revive
    - unparam
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gocritic
      - path: internal/mocks
        linters:
          - errcheck

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-checks:
      - commentedOutCode
      - nilValReturn
      - sloppyReassign
      - weakCond
      - octalLiteral
      - filepathJoin
      - preferFprint

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes: github.com/axon-go/axon-go
